import { test, expect } from "vitest";
import { enchantmentInfo } from "./enchantment";
import type { EnchantmentInfo } from "./enchantment";

test("enchantmentInfo should have only positive enchantment stone levels", () => {
	const expected: EnchantmentInfo[] = [
		{ enchantmentStone: 1, enchantmentSuccessChance: 15 },
		{ enchantmentStone: 2, enchantmentSuccessChance: 16.5 },
		{ enchantmentStone: 3, enchantmentSuccessChance: 18 },
		{ enchantmentStone: 4, enchantmentSuccessChance: 19.5 },
		{ enchantmentStone: 5, enchantmentSuccessChance: 21 },
		{ enchantmentStone: 6, enchantmentSuccessChance: 22.5 },
		{ enchantmentStone: 7, enchantmentSuccessChance: 24 },
		{ enchantmentStone: 8, enchantmentSuccessChance: 25.5 },
		{ enchantmentStone: 9, enchantmentSuccessChance: 27 },
		{ enchantmentStone: 10, enchantmentSuccessChance: 28.5 },
		{ enchantmentStone: 11, enchantmentSuccessChance: 30 },
		{ enchantmentStone: 12, enchantmentSuccessChance: 31.5 },
		{ enchantmentStone: 13, enchantmentSuccessChance: 33 },
		{ enchantmentStone: 14, enchantmentSuccessChance: 34.5 },
		{ enchantmentStone: 15, enchantmentSuccessChance: 36 },
		{ enchantmentStone: 16, enchantmentSuccessChance: 37.5 },
		{ enchantmentStone: 17, enchantmentSuccessChance: 39 },
		{ enchantmentStone: 18, enchantmentSuccessChance: 40.5 },
		{ enchantmentStone: 19, enchantmentSuccessChance: 42 },
		{ enchantmentStone: 20, enchantmentSuccessChance: 43.5 },
		{ enchantmentStone: 21, enchantmentSuccessChance: 45 },
		{ enchantmentStone: 22, enchantmentSuccessChance: 46.5 },
		{ enchantmentStone: 23, enchantmentSuccessChance: 48 },
		{ enchantmentStone: 24, enchantmentSuccessChance: 49.5 },
		{ enchantmentStone: 25, enchantmentSuccessChance: 51 },
		{ enchantmentStone: 26, enchantmentSuccessChance: 52.5 },
		{ enchantmentStone: 27, enchantmentSuccessChance: 54 },
		{ enchantmentStone: 28, enchantmentSuccessChance: 55.5 },
		{ enchantmentStone: 29, enchantmentSuccessChance: 57 },
		{ enchantmentStone: 30, enchantmentSuccessChance: 58.5 },
		{ enchantmentStone: 31, enchantmentSuccessChance: 60 },
		{ enchantmentStone: 32, enchantmentSuccessChance: 61.5 },
		{ enchantmentStone: 33, enchantmentSuccessChance: 63 },
		{ enchantmentStone: 34, enchantmentSuccessChance: 64.5 },
		{ enchantmentStone: 35, enchantmentSuccessChance: 66 },
		{ enchantmentStone: 36, enchantmentSuccessChance: 67.5 },
		{ enchantmentStone: 37, enchantmentSuccessChance: 69 },
		{ enchantmentStone: 38, enchantmentSuccessChance: 70.5 },
		{ enchantmentStone: 39, enchantmentSuccessChance: 72 },
		{ enchantmentStone: 40, enchantmentSuccessChance: 73.5 },
		{ enchantmentStone: 41, enchantmentSuccessChance: 75 },
		{ enchantmentStone: 42, enchantmentSuccessChance: 76.5 },
		{ enchantmentStone: 43, enchantmentSuccessChance: 78 },
		{ enchantmentStone: 44, enchantmentSuccessChance: 79.5 },
		{ enchantmentStone: 45, enchantmentSuccessChance: 80 }
	];

	const result = enchantmentInfo("eternal", 1, 0);

	expect(result).toEqual(expected);
});

test("enchantmentInfo should start with 0 success chance when stone level is not negative, and should stop at 80%", () => {
	const expected: EnchantmentInfo[] = [
		{ enchantmentStone: 45, enchantmentSuccessChance: 0 },
		{ enchantmentStone: 46, enchantmentSuccessChance: 1.5 },
		{ enchantmentStone: 47, enchantmentSuccessChance: 3 },
		{ enchantmentStone: 48, enchantmentSuccessChance: 4.5 },
		{ enchantmentStone: 49, enchantmentSuccessChance: 6 },
		{ enchantmentStone: 50, enchantmentSuccessChance: 7.5 },
		{ enchantmentStone: 51, enchantmentSuccessChance: 9 },
		{ enchantmentStone: 52, enchantmentSuccessChance: 10.5 },
		{ enchantmentStone: 53, enchantmentSuccessChance: 12 },
		{ enchantmentStone: 54, enchantmentSuccessChance: 13.5 },
		{ enchantmentStone: 55, enchantmentSuccessChance: 15 },
		{ enchantmentStone: 56, enchantmentSuccessChance: 16.5 },
		{ enchantmentStone: 57, enchantmentSuccessChance: 18 },
		{ enchantmentStone: 58, enchantmentSuccessChance: 19.5 },
		{ enchantmentStone: 59, enchantmentSuccessChance: 21 },
		{ enchantmentStone: 60, enchantmentSuccessChance: 22.5 },
		{ enchantmentStone: 61, enchantmentSuccessChance: 24 },
		{ enchantmentStone: 62, enchantmentSuccessChance: 25.5 },
		{ enchantmentStone: 63, enchantmentSuccessChance: 27 },
		{ enchantmentStone: 64, enchantmentSuccessChance: 28.5 },
		{ enchantmentStone: 65, enchantmentSuccessChance: 30 },
		{ enchantmentStone: 66, enchantmentSuccessChance: 31.5 },
		{ enchantmentStone: 67, enchantmentSuccessChance: 33 },
		{ enchantmentStone: 68, enchantmentSuccessChance: 34.5 },
		{ enchantmentStone: 69, enchantmentSuccessChance: 36 },
		{ enchantmentStone: 70, enchantmentSuccessChance: 37.5 },
		{ enchantmentStone: 71, enchantmentSuccessChance: 39 },
		{ enchantmentStone: 72, enchantmentSuccessChance: 40.5 },
		{ enchantmentStone: 73, enchantmentSuccessChance: 42 },
		{ enchantmentStone: 74, enchantmentSuccessChance: 43.5 },
		{ enchantmentStone: 75, enchantmentSuccessChance: 45 },
		{ enchantmentStone: 76, enchantmentSuccessChance: 46.5 },
		{ enchantmentStone: 77, enchantmentSuccessChance: 48 },
		{ enchantmentStone: 78, enchantmentSuccessChance: 49.5 },
		{ enchantmentStone: 79, enchantmentSuccessChance: 51 },
		{ enchantmentStone: 80, enchantmentSuccessChance: 52.5 },
		{ enchantmentStone: 81, enchantmentSuccessChance: 54 },
		{ enchantmentStone: 82, enchantmentSuccessChance: 55.5 },
		{ enchantmentStone: 83, enchantmentSuccessChance: 57 },
		{ enchantmentStone: 84, enchantmentSuccessChance: 58.5 },
		{ enchantmentStone: 85, enchantmentSuccessChance: 60 },
		{ enchantmentStone: 86, enchantmentSuccessChance: 61.5 },
		{ enchantmentStone: 87, enchantmentSuccessChance: 63 },
		{ enchantmentStone: 88, enchantmentSuccessChance: 64.5 },
		{ enchantmentStone: 89, enchantmentSuccessChance: 66 },
		{ enchantmentStone: 90, enchantmentSuccessChance: 67.5 },
		{ enchantmentStone: 91, enchantmentSuccessChance: 69 },
		{ enchantmentStone: 92, enchantmentSuccessChance: 70.5 },
		{ enchantmentStone: 93, enchantmentSuccessChance: 72 },
		{ enchantmentStone: 94, enchantmentSuccessChance: 73.5 },
		{ enchantmentStone: 95, enchantmentSuccessChance: 75 },
		{ enchantmentStone: 96, enchantmentSuccessChance: 76.5 },
		{ enchantmentStone: 97, enchantmentSuccessChance: 78 },
		{ enchantmentStone: 98, enchantmentSuccessChance: 79.5 },
		{ enchantmentStone: 99, enchantmentSuccessChance: 80 }
	];

	const result = enchantmentInfo("eternal", 55, 0);

	expect(result).toEqual(expected);
});

test("enchantmentInfo should cap at 50% for eternal items with enchantment levels 10 and above", () => {
	const expected: EnchantmentInfo[] = [
		{ enchantmentStone: 45, enchantmentSuccessChance: 0 },
		{ enchantmentStone: 46, enchantmentSuccessChance: 0.75 },
		{ enchantmentStone: 47, enchantmentSuccessChance: 1.5 },
		{ enchantmentStone: 48, enchantmentSuccessChance: 2.25 },
		{ enchantmentStone: 49, enchantmentSuccessChance: 3 },
		{ enchantmentStone: 50, enchantmentSuccessChance: 3.75 },
		{ enchantmentStone: 51, enchantmentSuccessChance: 4.5 },
		{ enchantmentStone: 52, enchantmentSuccessChance: 5.25 },
		{ enchantmentStone: 53, enchantmentSuccessChance: 6 },
		{ enchantmentStone: 54, enchantmentSuccessChance: 6.75 },
		{ enchantmentStone: 55, enchantmentSuccessChance: 7.5 },
		{ enchantmentStone: 56, enchantmentSuccessChance: 8.25 },
		{ enchantmentStone: 57, enchantmentSuccessChance: 9 },
		{ enchantmentStone: 58, enchantmentSuccessChance: 9.75 },
		{ enchantmentStone: 59, enchantmentSuccessChance: 10.5 },
		{ enchantmentStone: 60, enchantmentSuccessChance: 11.25 },
		{ enchantmentStone: 61, enchantmentSuccessChance: 12 },
		{ enchantmentStone: 62, enchantmentSuccessChance: 12.75 },
		{ enchantmentStone: 63, enchantmentSuccessChance: 13.5 },
		{ enchantmentStone: 64, enchantmentSuccessChance: 14.25 },
		{ enchantmentStone: 65, enchantmentSuccessChance: 15 },
		{ enchantmentStone: 66, enchantmentSuccessChance: 15.75 },
		{ enchantmentStone: 67, enchantmentSuccessChance: 16.5 },
		{ enchantmentStone: 68, enchantmentSuccessChance: 17.25 },
		{ enchantmentStone: 69, enchantmentSuccessChance: 18 },
		{ enchantmentStone: 70, enchantmentSuccessChance: 18.75 },
		{ enchantmentStone: 71, enchantmentSuccessChance: 19.5 },
		{ enchantmentStone: 72, enchantmentSuccessChance: 20.25 },
		{ enchantmentStone: 73, enchantmentSuccessChance: 21 },
		{ enchantmentStone: 74, enchantmentSuccessChance: 21.75 },
		{ enchantmentStone: 75, enchantmentSuccessChance: 22.5 },
		{ enchantmentStone: 76, enchantmentSuccessChance: 23.25 },
		{ enchantmentStone: 77, enchantmentSuccessChance: 24 },
		{ enchantmentStone: 78, enchantmentSuccessChance: 24.75 },
		{ enchantmentStone: 79, enchantmentSuccessChance: 25.5 },
		{ enchantmentStone: 80, enchantmentSuccessChance: 26.25 },
		{ enchantmentStone: 81, enchantmentSuccessChance: 27 },
		{ enchantmentStone: 82, enchantmentSuccessChance: 27.75 },
		{ enchantmentStone: 83, enchantmentSuccessChance: 28.5 },
		{ enchantmentStone: 84, enchantmentSuccessChance: 29.25 },
		{ enchantmentStone: 85, enchantmentSuccessChance: 30 },
		{ enchantmentStone: 86, enchantmentSuccessChance: 30.75 },
		{ enchantmentStone: 87, enchantmentSuccessChance: 31.5 },
		{ enchantmentStone: 88, enchantmentSuccessChance: 32.25 },
		{ enchantmentStone: 89, enchantmentSuccessChance: 33 },
		{ enchantmentStone: 90, enchantmentSuccessChance: 33.75 },
		{ enchantmentStone: 91, enchantmentSuccessChance: 34.5 },
		{ enchantmentStone: 92, enchantmentSuccessChance: 35.25 },
		{ enchantmentStone: 93, enchantmentSuccessChance: 36 },
		{ enchantmentStone: 94, enchantmentSuccessChance: 36.75 },
		{ enchantmentStone: 95, enchantmentSuccessChance: 37.5 },
		{ enchantmentStone: 96, enchantmentSuccessChance: 38.25 },
		{ enchantmentStone: 97, enchantmentSuccessChance: 39 },
		{ enchantmentStone: 98, enchantmentSuccessChance: 39.75 },
		{ enchantmentStone: 99, enchantmentSuccessChance: 40.5 },
		{ enchantmentStone: 100, enchantmentSuccessChance: 41.25 },
		{ enchantmentStone: 101, enchantmentSuccessChance: 42 },
		{ enchantmentStone: 102, enchantmentSuccessChance: 42.75 },
		{ enchantmentStone: 103, enchantmentSuccessChance: 43.5 },
		{ enchantmentStone: 104, enchantmentSuccessChance: 44.25 },
		{ enchantmentStone: 105, enchantmentSuccessChance: 45 },
		{ enchantmentStone: 106, enchantmentSuccessChance: 45.75 },
		{ enchantmentStone: 107, enchantmentSuccessChance: 46.5 },
		{ enchantmentStone: 108, enchantmentSuccessChance: 47.25 },
		{ enchantmentStone: 109, enchantmentSuccessChance: 48 },
		{ enchantmentStone: 110, enchantmentSuccessChance: 48.75 },
		{ enchantmentStone: 111, enchantmentSuccessChance: 49.5 },
		{ enchantmentStone: 112, enchantmentSuccessChance: 50 }
	];
	const result = enchantmentInfo("eternal", 55, 11);

	expect(result).toEqual(expected);
});

// TODO: add more tests
